name: Trigger wheel build

on:
  push:
    branches: [main, master, 'release*']
    tags: ['*']

jobs:
  build-wheels:
    if: github.repository == 'python/mypy'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Trigger script
        env:
          WHEELS_PUSH_TOKEN: ${{ secrets.WHEELS_PUSH_TOKEN }}
        run: ./misc/trigger_wheel_build.sh
